### ISSUE TITLE
how to overwrite font loading ? 

### ISSUE THREAD

**Issue by rsaccon** [mike1o1/ember-material-design#13]
Is there a way to overwrite (in the app) the font import statement at:
https://github.com/mike1o1/ember-material-design/blob/master/app/styles/core/typography.scss

Reason: for client side installed applications (e.g.: phonegap/cordova) I want to be able to load the fonts also when offline (in my specific case from local running webserver)

**Comment by mike1o1** [comment]
Hi, thanks for the feedback. There isn't a way to do this now, but I'll add the ability to do this for the next minor release, so that the font isn't hardcoded. In addition, I believe having the `@import` also blocks css parsing until it's finished, so that should be fixed anyway (it should be in the `<head>` section).

**Comment by mike1o1** [comment]
I added a section to the readme, but if you overwrite the `$font-family` variable in your .scss file before importing the `ember-material-design` file, you can specify your own font family. In addition, the `@import` has been removed.
